parameters:
#    vulture_main.example.class: Vulture\MainBundle\Example

services:
#    vulture_main.example:
#        class: %vulture_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
